trigger:
- master

pool:
  name: Default

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker_Hub'
    repository: 'aravind85tvr/ninja'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
     dev