trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker_Hub'
    repository: 'coreapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'