trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'coreapp-dev'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: dockerRegi